import { kv } from '@vercel/kv';
import jwt from 'jsonwebtoken';
import { cookies } from 'next/headers';

const JWT_SECRET = process.env.JWT_SECRET;
const GROQ_API_KEY = process.env.GROQ_API_KEY;

export async function POST(req) {
  try {
    const cookieStore = await cookies();
    const token = cookieStore.get('token');

    if (!token) {
      return new Response(JSON.stringify({ error: "Unauthorized. Please sign in to generate APIs." }), { status: 401 });
    }

    const decoded = jwt.verify(token.value, JWT_SECRET);
    if (!decoded || !decoded.userId) {
      return new Response(JSON.stringify({ error: "Invalid token" }), { status: 401 });
    }

    const { prompt } = await req.json();
    if (!prompt) {
      return new Response(JSON.stringify({ error: "Prompt is required" }), { status: 400 });
    }

    const dateKey = new Date().toISOString().split('T')[0];
    const rateLimitKey = `user:${decoded.userId}:ai_count:${dateKey}`;
    
    const count = await kv.get(rateLimitKey) || 0;
    
    if (count >= 3) {
      return new Response(JSON.stringify({ error: "Daily limit of 3 AI generations reached." }), { status: 429 });
    }

    const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${GROQ_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "openai/gpt-oss-120b",
        messages: [
          {
            role: "system",
            content: "You are a backend API architect. The user will describe an application. You must output ONLY a valid JSON object containing a 'resources' array. Each resource must have a 'name' (plural string) and a 'fields' array. Each field must have a 'name' (string) and a 'type' (strictly 'string', 'number', or 'boolean'). Do not wrap the JSON in markdown code blocks, return raw JSON only."
          },
          {
            role: "user",
            content: `Description: ${prompt}`
          }
        ],
        response_format: { type: "json_object" },
        temperature: 0.2,
        max_completion_tokens: 1500
      })
    });

    if (!response.ok) {
      const errText = await response.text();
      console.error("Groq Error:", errText);
      return new Response(JSON.stringify({ error: "Failed to fetch from Groq API" }), { status: 500 });
    }
    
    const data = await response.json();
    const content = data.choices[0].message.content;
    const parsedData = JSON.parse(content);
    
    if (parsedData.resources && Array.isArray(parsedData.resources)) {
      parsedData.resources.forEach(res => {
        if (res.fields && Array.isArray(res.fields)) {
          res.fields.forEach(field => {
            if (!field.mockType) field.mockType = 'auto';
          });
        }
      });

      await kv.incr(rateLimitKey);
      await kv.expire(rateLimitKey, 86400);

      return new Response(JSON.stringify({ resources: parsedData.resources }), { status: 200 });
    } else {
      return new Response(JSON.stringify({ error: "Invalid structure generated by AI" }), { status: 500 });
    }
  } catch (error) {
    console.error("Generate Route Error:", error);
    return new Response(JSON.stringify({ error: "Internal server error" }), { status: 500 });
  }
}
