import Discover from "../../components/Discover";
import { kv } from "@vercel/kv";
import { Suspense } from "react";
import Skeleton, { SkeletonTheme } from "react-loading-skeleton";

const CATEGORIES = ["All", "E-Commerce", "Social", "Fintech", "Utility"];

function DiscoverSkeleton() {
  return (
    <div className="relative min-h-screen text-white font-sans overflow-hidden bg-transparent">
      <div className="relative z-10 p-4 sm:p-8 md:p-12">
        <div className="max-w-[1400px] mx-auto space-y-12">
          <header className="flex flex-col md:flex-row md:items-end justify-between gap-6">
            <div className="space-y-4">
              <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-zinc-100">
                Discover Presets
              </h1>
              <p className="text-zinc-400 text-lg max-w-2xl leading-relaxed">
                Browse API schemas generated by the community. Click to instantly load them into your Builder.
              </p>
            </div>
          </header>

          <div className="flex overflow-x-auto pb-2 gap-3 scrollbar-hide">
            {CATEGORIES.map(cat => (
              <div key={cat} className="rounded-full px-4 py-1.5 h-8 w-24 border border-zinc-700 bg-zinc-800 animate-pulse" />
            ))}
          </div>

          <main>
            <SkeletonTheme baseColor="#18181b" highlightColor="#27272a">
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {[...Array(6)].map((_, i) => (
                  <div key={i} className="bg-zinc-900/50 border border-zinc-800 rounded-3xl p-6 h-[220px] flex flex-col justify-between">
                    <div>
                      <div className="flex justify-between items-start mb-4">
                        <Skeleton width={150} height={24} />
                        <Skeleton width={80} height={24} />
                      </div>
                      <Skeleton count={2} className="mb-4" />
                    </div>
                    <div className="flex justify-between items-center mt-4 border-t border-zinc-800/50 pt-4">
                      <Skeleton width={100} height={20} />
                      <div className="flex gap-2">
                        <Skeleton circle width={32} height={32} />
                        <Skeleton circle width={32} height={32} />
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </SkeletonTheme>
          </main>
        </div>
      </div>
    </div>
  );
}

async function DiscoverData() {
  let initialPresets = [];
  try {
    const presetIds = await kv.zrange('global:presets', 0, 49, { rev: true });
    if (presetIds && presetIds.length > 0) {
      const presetPromises = presetIds.map(id => kv.hgetall(`preset:${id}`));
      const resolved = await Promise.all(presetPromises);
      const loadedPresets = resolved.filter(Boolean);
      initialPresets = loadedPresets.map(p => ({
        ...p,
        cloneCount: Math.floor(Math.random() * 451) + 50,
        category: CATEGORIES[Math.floor(Math.random() * (CATEGORIES.length - 1)) + 1]
      }));
    }
  } catch (e) {
    // silent fail
  }
  return <Discover initialPresets={initialPresets} />;
}

export default function DiscoverPage() {
  return (
    <Suspense fallback={<DiscoverSkeleton />}>
      <DiscoverData />
    </Suspense>
  );
}
