"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import Skeleton from "../../components/Skeleton";
import SpecularButton from "../../components/SpecularButton";
import DotField from "../../components/DotField";

export default function Discover() {
  const router = useRouter();
  const [presets, setPresets] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  
  useEffect(() => {
    const fetchPresets = async () => {
      try {
        const res = await fetch('/api/presets');
        if (!res.ok) throw new Error('Failed to fetch presets');
        const data = await res.json();
        setPresets(data.presets || []);
      } catch (err) {
        console.error(err);
        setError("Failed to load community presets.");
      } finally {
        setLoading(false);
      }
    };
    fetchPresets();
  }, []);

  const handleUsePreset = (presetId) => {
    router.push(`/?preset=${presetId}`);
  };

  return (
    <div className="relative min-h-screen bg-[#050505] text-white font-sans selection:bg-indigo-500/30 overflow-hidden">
      <div className="absolute inset-0 z-0">
        <DotField
          dotRadius={1.5}
          dotSpacing={14}
          bulgeStrength={67}
          glowRadius={160}
          sparkle={true}
          waveAmplitude={0}
        />
      </div>
      
      <div className="relative z-10 p-4 sm:p-8 md:p-12">
        <div className="max-w-[1400px] mx-auto space-y-12">
        <header className="flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div className="space-y-4">
            <div className="flex items-center gap-4">
              <Link href="/" className="p-2 bg-white/5 hover:bg-white/10 rounded-xl transition-colors text-neutral-400 hover:text-white">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                </svg>
              </Link>
              <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-emerald-400 via-cyan-400 to-indigo-400 animate-gradient-x">
                Discover Presets
              </h1>
            </div>
            <p className="text-neutral-400 text-lg max-w-2xl leading-relaxed ml-14">
              Browse API schemas generated by the community. Click to instantly load them into your Builder.
            </p>
          </div>
        </header>

        <main>
          {loading ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {[...Array(6)].map((_, i) => (
                <Skeleton key={i} className="h-48 w-full rounded-2xl" />
              ))}
            </div>
          ) : error ? (
            <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-6 rounded-2xl text-center">
              {error}
            </div>
          ) : presets.length === 0 ? (
            <div className="bg-white/[0.02] border border-white/5 p-12 rounded-3xl text-center">
              <h3 className="text-xl font-semibold text-neutral-300 mb-2">No presets found</h3>
              <p className="text-neutral-500">Be the first to publish an API preset!</p>
            </div>
          ) : (
            <motion.div 
              className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5 }}
            >
              <AnimatePresence>
                {presets.map((preset, idx) => (
                  <motion.div
                    key={preset.presetId}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.4, delay: idx * 0.05 }}
                    className="group bg-white/[0.03] backdrop-blur-xl border border-white/10 shadow-lg rounded-3xl p-6 relative overflow-hidden hover:bg-white/[0.05] transition-all flex flex-col h-full"
                  >
                    <div className="absolute -top-16 -right-16 w-32 h-32 bg-cyan-500/10 rounded-full blur-3xl group-hover:bg-cyan-500/20 transition-all pointer-events-none"></div>
                    
                    <div className="flex-1 space-y-4 relative z-10">
                      <div className="flex justify-between items-start gap-4">
                        <h3 className="text-xl font-bold text-white line-clamp-1">{preset.title}</h3>
                        <span className="px-2.5 py-1 bg-black/40 text-neutral-400 text-xs rounded-md border border-white/5 whitespace-nowrap">
                          {preset.resources?.length || 0} endpoints
                        </span>
                      </div>
                      
                      <p className="text-sm text-neutral-400 line-clamp-3">
                        {preset.description || "No description provided."}
                      </p>
                      
                      <div className="flex items-center gap-2 mt-4 pt-4 border-t border-white/5">
                        <div className="w-6 h-6 rounded-full bg-gradient-to-tr from-indigo-500 to-cyan-500 flex items-center justify-center text-[10px] font-bold text-white shadow-sm">
                          {preset.author?.[0]?.toUpperCase() || '?'}
                        </div>
                        <span className="text-xs text-neutral-300 font-medium">{preset.author}</span>
                        <span className="text-xs text-neutral-600 ml-auto">
                          {new Date(preset.createdAt).toLocaleDateString()}
                        </span>
                      </div>
                    </div>
                    
                    <div className="mt-6 relative z-10" onClick={() => handleUsePreset(preset.presetId)}>
                      <SpecularButton className="w-full justify-center !bg-cyan-500/10 hover:!bg-cyan-500/20 !border-cyan-500/30 text-cyan-300 transition-colors" autoAnimate>
                        <span className="flex items-center gap-2">
                          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                          </svg>
                          Use this Preset
                        </span>
                      </SpecularButton>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>
            </motion.div>
          )}
        </main>
      </div>
      </div>
    </div>
  );
}
