"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import Skeleton, { SkeletonTheme } from "react-loading-skeleton";
import DotField from "../../components/DotField";

export default function Discover() {
  const router = useRouter();
  const [presets, setPresets] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  
  useEffect(() => {
    const fetchPresets = async () => {
      try {
        const res = await fetch('/api/presets');
        if (!res.ok) throw new Error('Failed to fetch presets');
        const data = await res.json();
        setPresets(data.presets || []);
      } catch (err) {
        console.error(err);
        setError("Failed to load community presets.");
      } finally {
        setLoading(false);
      }
    };
    fetchPresets();
  }, []);

  const handleUsePreset = (presetId) => {
    router.push(`/?preset=${presetId}`);
  };

  return (
    <div className="relative min-h-screen text-white font-sans selection:bg-zinc-800 overflow-hidden bg-transparent">
      {/* <div className="absolute inset-0 z-0">
        <DotField
          dotRadius={1.5}
          dotSpacing={14}
          bulgeStrength={67}
          glowRadius={160}
          sparkle={true}
          waveAmplitude={0}
        />
      </div> */}
      
      <div className="relative z-10 p-4 sm:p-8 md:p-12">
        <div className="max-w-[1400px] mx-auto space-y-12">
        <header className="flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div className="space-y-4">
            <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-zinc-100">
              Discover Presets
            </h1>
            <p className="text-zinc-400 text-lg max-w-2xl leading-relaxed">
              Browse API schemas generated by the community. Click to instantly load them into your Builder.
            </p>
          </div>
        </header>

        <main>
          {loading ? (
            <SkeletonTheme baseColor="#18181b" highlightColor="#27272a">
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {[...Array(6)].map((_, i) => (
                  <div key={i} className="bg-zinc-900/50 border border-zinc-800 rounded-3xl p-6 h-[220px] flex flex-col justify-between">
                    <div>
                      <div className="flex justify-between items-start mb-4">
                        <Skeleton width={150} height={24} />
                        <Skeleton width={80} height={24} />
                      </div>
                      <Skeleton count={2} className="mb-4" />
                    </div>
                    <Skeleton height={45} borderRadius={12} />
                  </div>
                ))}
              </div>
            </SkeletonTheme>
          ) : error ? (
            <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-6 rounded-2xl text-center">
              {error}
            </div>
          ) : presets.length === 0 ? (
            <div className="bg-zinc-900/50 border border-zinc-800 p-12 rounded-3xl text-center">
              <h3 className="text-xl font-semibold text-zinc-300 mb-2">No presets found</h3>
              <p className="text-zinc-500">Be the first to publish an API preset!</p>
            </div>
          ) : (
            <motion.div 
              className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5 }}
            >
              <AnimatePresence>
                {presets.map((preset, idx) => (
                  <motion.div
                    key={preset.presetId}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.4, delay: idx * 0.05 }}
                    className="group bg-zinc-900/50 border border-zinc-800 shadow-sm rounded-3xl p-6 relative overflow-hidden hover:bg-zinc-800/50 transition-all flex flex-col h-full"
                  >
                    <div className="flex-1 space-y-4 relative z-10">
                      <div className="flex justify-between items-start gap-4">
                        <h3 className="text-xl font-bold text-white line-clamp-1">{preset.title}</h3>
                        <span className="px-2.5 py-1 bg-zinc-950 text-zinc-400 text-xs rounded-md border border-zinc-800 whitespace-nowrap">
                          {preset.resources?.length || 0} endpoints
                        </span>
                      </div>
                      
                      <p className="text-sm text-zinc-400 line-clamp-3">
                        {preset.description || "No description provided."}
                      </p>
                      
                      <div className="flex items-center gap-2 mt-4 pt-4 border-t border-zinc-800">
                        <div className="w-6 h-6 rounded-full bg-zinc-800 border border-zinc-700 flex items-center justify-center text-[10px] font-bold text-white shadow-sm">
                          {preset.author?.[0]?.toUpperCase() || '?'}
                        </div>
                        <span className="text-xs text-zinc-300 font-medium">{preset.author}</span>
                        <span className="text-xs text-zinc-500 ml-auto">
                          {new Date(preset.createdAt).toLocaleDateString()}
                        </span>
                      </div>
                    </div>
                    
                    <div className="mt-6 relative z-10">
                      <button 
                        onClick={() => handleUsePreset(preset.presetId)}
                        className="w-full flex items-center justify-center gap-2 py-3 bg-white text-black hover:bg-zinc-200 text-sm font-semibold rounded-xl transition-colors shadow-sm"
                      >
                        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                        </svg>
                        Use this Preset
                      </button>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>
            </motion.div>
          )}
        </main>
      </div>
      </div>
    </div>
  );
}
